// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxvaudwezruoflcjijmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4dmF1ZHdlenJ1b2ZsY2ppam1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzMxMDMsImV4cCI6MjA2NzU0OTEwM30.wNez1vMzOHYFiwoD94iK0OK7ZdKxsIdcDiEpa6xaPes";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});